//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentSoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int ID { get; set; }
        public Nullable<int> IdDoctor { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public string NombrePaciente { get; set; }
        public string Edad { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NombreDoctor { get; set; }
        public string Motivo { get; set; }
        public string Diagnostico { get; set; }
        public string Procedimiento { get; set; }
        public string Observaciones { get; set; }
        public string Indicaciones { get; set; }
        public byte[] Foto { get; set; }
        public string Plan_Tratamiento { get; set; }
        public byte[] imagen_odontograma { get; set; }
    }
}
