//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentSoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int ID { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<int> EdadCliente { get; set; }
        public string SexoCliente { get; set; }
        public string NombreDoctor { get; set; }
        public string EspecialidadDoctor { get; set; }
        public string Procesos { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> Pago { get; set; }
        public Nullable<double> Total { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
