//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentSoft.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GRUDENTEntities : DbContext
    {
        public GRUDENTEntities()
            : base("name=GRUDENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Diagnostico> Diagnostico { get; set; }
        public virtual DbSet<Doctores> Doctores { get; set; }
        public virtual DbSet<PacienteN> PacienteN { get; set; }
        public virtual DbSet<Procedimientos> Procedimientos { get; set; }
        public virtual DbSet<Procesos> Procesos { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<HistoricoPago> HistoricoPago { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesPermisos> RolesPermisos { get; set; }
    }
}
