//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentSoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoPago
    {
        public int ID { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<double> Deuda { get; set; }
        public Nullable<double> Abono { get; set; }
        public Nullable<double> Resto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Comentario { get; set; }
    }
}
