//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentSoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteN
    {
        public int ID { get; set; }
        public string Documento { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaDeNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string GrupoSanguineo { get; set; }
        public string ARS { get; set; }
        public string NSS { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Direccion { get; set; }
        public byte[] Foto { get; set; }
        public string TutorNombre { get; set; }
        public string TutorTelefono { get; set; }
        public string TutorCedula { get; set; }
    }
}
