//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentSoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procesos
    {
        public int ID { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdDoctor { get; set; }
        public Nullable<int> IdProceso { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Proceso { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> Pago { get; set; }
        public Nullable<double> Pendiente { get; set; }
        public string NombrePaciente { get; set; }
        public string NombreDoctor { get; set; }
        public string Estatus { get; set; }
    }
}
