//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentSoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesPermisos
    {
        public int Permisos_IdPermiso { get; set; }
        public int Roles_IdRol { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Permisos Permisos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
